@echo off
title DostAI Auto-Launcher
echo Waking up DostAI Backend...
start cmd /k "cd backend && node server.js"
echo Waking up DostAI Frontend...
start cmd /k "cd frontend && npm run dev"
echo Launching local browser...
start http://localhost:5173